[tool.poetry]
name = "rocksdbdict"
version = "0.8.0"
description = ""
authors = ["Adam Marples <adammarples@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
faust-streaming-rocksdb = "^0.8.0"

[tool.poetry.dev-dependencies]
pytest = "^6.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


